CREATE TABLE tbl_document (
    id INT PRIMARY KEY AUTO_INCREMENT,
    file_type VARCHAR(255),
    file_name VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);
